created_by: mukesh@mightybot.ai
description: Schema representing the configuration of a policy including its attributes and status.
is_active: true
is_primary: true
last_modified_by: mukesh@mightybot.ai
schema_definition:
    additionalProperties: false
    properties:
        address:
            type: string
        annualincome:
            type: number
        applicantname:
            type: string
        creditscore:
            type: integer
        dob:
            format: date
            type: string
        interestrate:
            type: string
        loantype:
            type: string
        phonenumber:
            type: string
        policy_name:
            type: string
        policy_type:
            type: string
        ssn/orpan:
            type: string
    required:
        - policy_name
        - policy_type
        - applicantname
        - dob
        - ssn/orpan
        - phonenumber
    type: object
tenant_id: 0aedf8cd-f286-4177-b61c-8ceca47eea47
title: Policy Configuration Data
type: WEBHOOK
version: "1.0"
workflow_id: 56b0ae10-0ff5-41d4-a46a-a7c4924c2073
