accepted_file_types:
    - .pdf
    - .xlsx
description: G702/G703 AIA pay applications from general contractors
entity_schema_id: b86a0981-ffe8-4dbf-8cc3-bd2e2d6a75e2
extraction_model: null
extraction_schema: draw-and-funding-amounts
