accepted_file_types:
    - .pdf
    - .xlsx
description: G702/G703 AIA pay applications from general contractors
entity_schema_id: bfae4dba-d2ef-44ed-9042-958161105ffd
extraction_model: null
extraction_schema: document_package_schema
