created_by: mukesh@mightybot.ai
description: Schema for configuring policy agent workflow with necessary parameters.
is_active: true
is_primary: true
last_modified_by: mukesh@mightybot.ai
schema_definition:
    additionalProperties: false
    properties:
        address:
            type: string
        annualincome:
            type: number
        applicantname:
            type: string
        convert_unsupported_files:
            type: string
        creditscore:
            type: number
        dob:
            format: date
            type: string
        interestrate:
            type: number
        loantype:
            type: string
        phonenumber:
            type: string
        ssn/orpan:
            type: string
    required:
        - applicantname
        - dob
        - annualincome
    type: object
tenant_id: 0aedf8cd-f286-4177-b61c-8ceca47eea47
title: Policy Agent Configuration
type: API_REQUEST
version: "1.0"
workflow_id: 123d46e1-36b9-4ac9-87f4-4cab64645545
