created_by: mukesh@mightybot.ai
description: Schema representing the configuration for a policy agent workflow.
is_active: true
is_primary: true
last_modified_by: mukesh@mightybot.ai
schema_definition:
    additionalProperties: false
    properties:
        address:
            type: string
        annualincome:
            type: string
        applicantname:
            type: string
        creditscore:
            type: number
        dob:
            format: date
            type: string
        loantype:
            type: string
        phonenumber:
            type: string
    required:
        - loantype
    type: object
tenant_id: 0aedf8cd-f286-4177-b61c-8ceca47eea47
title: Policy Agent Configuration
type: WEBHOOK
version: "1.0"
workflow_id: deef31de-6238-4152-80e8-482cc5362909
