created_by: mukesh@mightybot.ai
description: Schema representing the configuration settings for a policy agent workflow.
is_active: true
is_primary: true
last_modified_by: mukesh@mightybot.ai
schema_definition:
    additionalProperties: false
    properties:
        agent_name:
            type: string
        classifications:
            type: array
        convert_unsupported:
            type: boolean
        supported_types:
            type: array
    required:
        - agent_name
    type: object
tenant_id: 0aedf8cd-f286-4177-b61c-8ceca47eea47
title: Policy Agent Configuration
type: API_REQUEST
version: "1.0"
workflow_id: fdf08f70-e63b-4109-813f-92a0eded4161
